export default {
  FETCH_LOCATIONS_SUCCESS: 'locations/FETCH_LOCATIONS_SUCCESS',
  FETCH_LOCATIONS_REQUEST: 'locations/FETCH_LOCATIONS_REQUEST',
  FETCH_LOCATIONS_FAILURE: 'locations/FETCH_LOCATIONS_FAILURE',
};
