export default {
  FETCH_CHARACTERS_REQUEST: 'characters/FETCH_CHARACTERS_REQUEST',
  FETCH_CHARACTERS_SUCCESS: 'characters/FETCH_CHARACTERS_SUCCESS',
  FETCH_CHARACTERS_FAILURE: 'characters/FETCH_CHARACTERS_FAILURE',
};
