export default {
  FETCH_EPISODES_REQUEST: 'characters/FETCH_EPISODES_REQUEST',
  FETCH_EPISODES_SUCCESS: 'characters/FETCH_EPISODES_SUCCESS',
  FETCH_EPISODES_FAILURE: 'characters/FETCH_EPISODES_FAILURE',
};
